spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: librarydb
  zipkin:
    base-url: http://localhost:9411/

  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)    
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka/
      
