server:
  port: 8082
  
spring:
  application:
    name: BookQuery
    
kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: gid
      auto-offset-reset: latest
      bootstrap-servers: localhost:9092
      enable-auto-commit: true
      properties:
        spring:
          json:
            trusted:
              packages : "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
