server:
  port: 8084

spring:
  application:
    name: BorrowingService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: librarydb

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8761/eureka
